services:
  victim_app:
    build:
      context: .
      dockerfile: victim_app/Dockerfile
    container_name: victim_app
    ports:
      - "8000:8000"
    networks:
      - labnet

  firewall_app:
    build:
      context: .
      dockerfile: firewall_app/Dockerfile
    container_name: firewall_app
    ports:
      - "8080:8080"
    depends_on:
      - victim_app
    networks:
      - labnet

  attacker:
    build:
      context: .
      dockerfile: attacker/Dockerfile
    networks:
      - labnet
    environment:
      - TARGET_URL=http://firewall_app:8080/
    profiles:
      - manual

networks:
  labnet:
    driver: bridge
